### ISSUE TITLE
<H3> tag not displaying properly

### ISSUE THREAD

**Issue by Beatrix-droid** [Beatrix-droid/tic-tac-toe#1]
The h3 tag in the tic tac toe page should display the either "player X" or "player O" depending on whose turn it is.
It is currently only displaying "Player X".

**Comment by IwonaBaran** [comment]
Can I work on this?

**Comment by Beatrix-droid** [comment]
> Can I work on this?

of course You  can!

**Comment by Saif-S** [comment]
I would like to work on this.

**Comment by Beatrix-droid** [comment]
@IwonaBaran  Hi, are there any news on the project? There is no rush, I was just asking because I want to stay updated

**Comment by IwonaBaran** [comment]
Hi, sorry about the delay in getting back to you. I've been trying to fix this but no success so far. I need to learn more about event listeners in js. I'll keep trying but if someone else wants to work on this I would be happy to see the solution.

**Comment by Beatrix-droid** [comment]
@IwonaBaran  it;s no problem at all! I myself am no expert in Js as  Python is my main language. In fact, if its of any help, I wrote this program following this 10 minute video, mostly to try and see how some concepts that I had learnt in python mapped onto JS, so that i could slowly begin to learn this language with a gentle introduction.
Maybe this could be of use top you?

https://www.youtube.com/watch?v=2UR8gSnRU28

**Comment by IwonaBaran** [comment]
I recommend Traversy Media channel on youtube for JS tutorials and small projects.
Thanks for the video, I fixed this.

**Comment by Beatrix-droid** [comment]
thank you for the suggestion, I will definitely check them out! I'm always eager to hear about any new learning resources I have not heard of!
I have mostly been learning through Free code camp! If you haven't already you should definitely check them out!

**Comment by IwonaBaran** [comment]
Thank you so much, will definitely check that!

**Comment by Saif-S** [comment]
I would like to work on this.

**Comment by Beatrix-droid** [comment]
@Saif-S I am really really sorry, this issue was already fixed and I mistakenly forgot to close it!
